export const INDIAN_CROPS = [
    "Rice",
    "Wheat",
    "Maize",
    "Jowar (Sorghum)",
    "Bajra (Pearl Millet)",
    "Ragi (Finger Millet)",
    "Sugarcane",
    "Cotton",
    "Jute",
    "Groundnut",
    "Mustard",
    "Coconut",
    "Sesame",
    "Soyabean",
    "Sunflower",
    "Tea",
    "Coffee",
    "Rubber",
    "Gram (Chickpea)",
    "Tur (Pigeon Pea)",
    "Urad (Black Gram)",
    "Moong (Green Gram)",
    "Masur (Lentil)",
    "Tobacco",
    "Potato",
    "Mango",
    "Banana",
    "Citrus (Orange/Lemon)",
    "Guava",
    "Grapes",
    "Apple",
    "Pomegranate",
    "Papaya",
    "Pineapple",
    "Tomato",
    "Onion",
    "Brinjal",
    "Cabbage",
    "Cauliflower",
    "Chili",
    "Neem Tree",
    "Peepal Tree",
    "Banyan Tree",
    "Teak Wood",
    "Sal Tree",
    "Sheesham (Indian Rosewood)",
    "Sandalwood",
    "Eucalyptus",
    "Bamboo",
    "Areca Nut (Betel Nut)"
];
