import { CattleListing, CommunityPost, Field, HarvestRecord, Insight, MarketplaceItem, MarketPrice, RentalEquipment, Task, Weather, YieldData } from "./types";

// User
export const USER: { name: string; avatarUrl: string } = {
  name: "Farmer John",
  avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCk4wl1QwR6U0Trv1hTG7QralNDkeZ7b6BxmOOu4N03SvWdezUz6Aim8ASl_-11KNwaod6UsiD7Nkx_gJSzrLWglADEnpIps7LW4CUR_aEGHGp23teU3sF2LDpaem0kAzfbq8ADqcsoGtCEhVOHTHyw2Vbw0SsrEQKR0wjA8KRK4ybMmXvxVF4Jo_nqrTis1prbFwnr0HBaX3HAjNxAiJAGA0RzllagDsME4e1o-8gd4JSGfcer9VNmiDxAEqGcs7N-EEO573p67Vl",
};

// Fields
export const FIELDS: Field[] = [
  {
    id: "f1",
    name: "Field A",
    crop: "Soybeans",
    acres: 45,
    status: "Healthy",
    growthStage: "Vegetative (V3)",
    maturityPercentage: 45,
    lastIrrigated: "2023-10-23T09:00:00Z",
    moisturePercentage: 12,
    coordinates: [
      [78.1460, 11.6643],
      [78.1500, 11.6643],
      [78.1500, 11.6600],
      [78.1460, 11.6600],
      [78.1460, 11.6643]
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCBqJfznq1ePC9Zc4qWegNo2g2muOR8sv0xYcGL6WNftQIY7OUcenCNTjjtuoan6R_C_leWbxIizcsLeTDozCUqikx4VzWWhDOjGk8Gne8K154HIV6HpuZ0r4iC06X3WajovJ_G4CGZn_DPwHj75jXnN6qWWsMQ-OsyDIG-0he9ESq-3e5lHCyUa02pxizcYOy-KwOA2CjjOygzo5ocfPFU7ZV0JZMLjI0wOS5VVTxvjjmcebw9TsIF02ihGxuvxNeZTfbrYGP7pj1U",
  },
  {
    id: "f2",
    name: "Field B",
    crop: "Winter Wheat",
    acres: 120,
    status: "Dry",
    growthStage: "Harvest Ready",
    maturityPercentage: 98,
    lastIrrigated: "2023-10-22T14:30:00Z",
    moisturePercentage: 8,
    coordinates: [
      [78.1520, 11.6660],
      [78.1600, 11.6660],
      [78.1600, 11.6600],
      [78.1520, 11.6600],
      [78.1520, 11.6660]
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuA70x2kRpfMxM1IRIshuDMJYbwAukd2q3miFIzSC411_F-3ff8fvaRMbopKeZy2qNljUSwIiwxbOCuTrD2cPb0g26SEv0CYPNkjrH2SZOfP9LSekGyFSzbv5yMIa5d_1cnR8t9JLKIw5rtcaRvbc7uMJ28UCER8nGlQbApVr9PxP3BEj1VIlINs03MZkvsUNH7QqM7Alg7pFC2XvCt93XpcpTToCwkSgIMnQInLL8eJP1hMYlWo-61Ai_NdSWcx2tzYv3MUxn1wpacz",
  },
  {
    id: "f3",
    name: "Field C",
    crop: "Corn",
    acres: 85,
    status: "Healthy",
    growthStage: "Flowering (R1)",
    maturityPercentage: 60,
    lastIrrigated: "2023-10-24T08:00:00Z",
    moisturePercentage: 15,
    coordinates: [
      [78.1460, 11.6580],
      [78.1550, 11.6580],
      [78.1550, 11.6540],
      [78.1460, 11.6540],
      [78.1460, 11.6580]
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCBqJfznq1ePC9Zc4qWegNo2g2muOR8sv0xYcGL6WNftQIY7OUcenCNTjjtuoan6R_C_leWbxIizcsLeTDozCUqikx4VzWWhDOjGk8Gne8K154HIV6HpuZ0r4iC06X3WajovJ_G4CGZn_DPwHj75jXnN6qWWsMQ-OsyDIG-0he9ESq-3e5lHCyUa02pxizcYOy-KwOA2CjjOygzo5ocfPFU7ZV0JZMLjI0wOS5VVTxvjjmcebw9TsIF02ihGxuvxNeZTfbrYGP7pj1U",
  },
];

// Tasks — dates are spread across the current week
export const TASKS: Task[] = [
  {
    id: "t1",
    title: "Wheat Field A - Sowing",
    description: "Use Machinery A2 for row sowing in north section.",
    date: "2026-02-14",
    startTime: "08:00",
    endTime: "10:00",
    duration: "2 hrs",
    status: "Completed",
    type: "Machinery",
    priority: "High",
    location: "Field A - North",
  },
  {
    id: "t2",
    title: "Irrigation Check",
    description: "Inspect drip lines in Sector 4 for leaks and pressure issues.",
    date: "2026-02-14",
    startTime: "11:30",
    endTime: "13:00",
    duration: "1.5 hrs",
    status: "In Progress",
    type: "Water",
    priority: "High",
    location: "Sector 4",
  },
  {
    id: "t3",
    title: "Apply NPK Fertilizer",
    description: "Corn Fields - Sector 2 & 3. Mix ratio: 19-19-19.",
    date: "2026-02-14",
    startTime: "14:00",
    endTime: "16:00",
    duration: "2 hrs",
    status: "Pending",
    type: "Chemical",
    priority: "Medium",
    workerAvatars: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDEpsGH1EPzxHWTeVlm-1pZkYTSAShYzajtoy01A05kTd_9feZSdXBknbQREJDv5V-CMe7d6ZHwOxzDjyg_A_Pf70UFsr9RgN7FO_o3hKYZL--G82GFx9iP3B03aGkGd-NYHoksCJC1MygMRb4Cj_OY0VmudnLtpVq_3VeBugGIXt3cTaTn0I0h0qHGFdzajIwln0TvzzQeMM94MA6OO2yM03tlqr6mfkTKME3TtMPY0IzLAhIWBx8g1iMlAbiZFwOCmFv2uVvmwOsM",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAbcnNLaLYOzGiVp_ulJAoda2jUKYEmgk0r1NZv3iQMeqjssbTNFjHVKdEMEY-Tvb_1gnUxC43-6Hulikxo0L0WZ_5DX5wPPNE_2RacrgqbQ3ZXjN4fJxaRR4VbbXJEU1myds-XSKe-r6erWbJ2ZK6TX426Y2HRdTEquZU9T_lw2CXQ663T5Fio8IYR4S2lNkvjw2_GuxGcXETakAwR-HrIRWrvPr-KMHNU9kEpMWS8zZvhzNl9M9hsVhiqJGmGZdTePSQFxpNke9vP"
    ],
  },
  {
    id: "t4",
    title: "Fence Repair - East Boundary",
    description: "Fix broken wire fence near the canal side. Bring wire cutters.",
    date: "2026-02-14",
    startTime: "16:30",
    endTime: "18:00",
    duration: "1.5 hrs",
    status: "Pending",
    type: "Maintenance",
    priority: "Low",
    location: "East Boundary",
  },
  {
    id: "t5",
    title: "Soil Sample Collection",
    description: "Collect samples from 6 points across Field B for lab analysis.",
    date: "2026-02-15",
    startTime: "07:00",
    endTime: "09:00",
    duration: "2 hrs",
    status: "Pending",
    type: "Maintenance",
    priority: "High",
    location: "Field B",
  },
  {
    id: "t6",
    title: "Pesticide Spray - Neem Oil",
    description: "Organic neem oil application on tomato beds. Use mist setting.",
    date: "2026-02-15",
    startTime: "10:00",
    endTime: "12:00",
    duration: "2 hrs",
    status: "Pending",
    type: "Chemical",
    priority: "Medium",
    location: "Greenhouse A",
  },
  {
    id: "t7",
    title: "Harvester Maintenance",
    description: "Oil change, blade sharpening, and belt check on Kubota DC-70.",
    date: "2026-02-16",
    startTime: "08:00",
    endTime: "11:00",
    duration: "3 hrs",
    status: "Pending",
    type: "Machinery",
    priority: "Medium",
  },
  {
    id: "t8",
    title: "Canal Water Release",
    description: "Open sluice gate for scheduled canal irrigation batch. Monitor flow.",
    date: "2026-02-13",
    startTime: "06:00",
    endTime: "08:00",
    duration: "2 hrs",
    status: "Completed",
    type: "Water",
    priority: "High",
    location: "Main Canal",
  },
  {
    id: "t9",
    title: "Weeding - Corn Field",
    description: "Manual weeding between rows in Sector 2. Team of 4 workers.",
    date: "2026-02-13",
    startTime: "09:00",
    endTime: "13:00",
    duration: "4 hrs",
    status: "Completed",
    type: "Maintenance",
    priority: "Medium",
    location: "Sector 2",
    workerAvatars: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDEpsGH1EPzxHWTeVlm-1pZkYTSAShYzajtoy01A05kTd_9feZSdXBknbQREJDv5V-CMe7d6ZHwOxzDjyg_A_Pf70UFsr9RgN7FO_o3hKYZL--G82GFx9iP3B03aGkGd-NYHoksCJC1MygMRb4Cj_OY0VmudnLtpVq_3VeBugGIXt3cTaTn0I0h0qHGFdzajIwln0TvzzQeMM94MA6OO2yM03tlqr6mfkTKME3TtMPY0IzLAhIWBx8g1iMlAbiZFwOCmFv2uVvmwOsM",
    ],
  },
  {
    id: "t10",
    title: "Tractor Plowing - Field C",
    description: "Deep plowing for next season preparation. 12-inch depth.",
    date: "2026-02-12",
    startTime: "07:30",
    endTime: "12:00",
    duration: "4.5 hrs",
    status: "Completed",
    type: "Machinery",
    priority: "High",
    location: "Field C",
  },
];

// Weather
export const WEATHER: Weather = {
  temp: 72,
  condition: "Partly Cloudy",
  humidity: 12,
  windSpeed: 8,
  alert: {
    type: "High Wind",
    message: "High Wind Warning",
  },
};

// Market Prices
export const MARKET_PRICES: MarketPrice[] = [
  {
    id: "m1",
    commodity: "Wheat",
    symbol: "ZW",
    price: 6.10,
    unit: "bu",
    change: -0.50,
    trend: "down",
    exchange: "Local Exchange",
    chartData: [6.20, 6.18, 6.15, 6.12, 6.10],
  },
  {
    id: "m2",
    commodity: "Soybeans",
    symbol: "ZS",
    price: 13.40,
    unit: "bu",
    change: 0.85,
    trend: "up",
    exchange: "Global",
    chartData: [13.20, 13.25, 13.30, 13.35, 13.40],
  },
  {
    id: "m3",
    commodity: "Oats",
    symbol: "ZO",
    price: 3.55,
    unit: "bu",
    change: 0.12,
    trend: "up",
    exchange: "Local Exchange",
    chartData: [3.50, 3.51, 3.53, 3.54, 3.55],
  },
  {
    id: "m4",
    commodity: "Canola",
    symbol: "RS",
    price: 715.2,
    unit: "bu",
    change: -1.4,
    trend: "down",
    exchange: "Global",
    chartData: [725, 720, 718, 716, 715.2],
  },
];

// Yield Data
export const YIELD_HISTORY: YieldData[] = [
  { year: 2019, yield: 160, total: 198000 },
  { year: 2020, yield: 172, total: 213000 },
  { year: 2021, yield: 165, total: 204000 },
  { year: 2022, yield: 180, total: 223000 },
  { year: 2023, yield: 184.2, total: 228000 },
];

// Insights
export const INSIGHTS: Insight[] = [
  {
    id: "i1",
    type: "positive",
    title: "Nitrogen Optimization Success",
    description: "Yield is 5% higher in Field 4 due to optimized nitrogen application in early June.",
    actionLabel: "View Field 4 Details",
  },
  {
    id: "i2",
    type: "warning",
    title: "Moisture Alert",
    description: "Field 2 is underperforming by 3% compared to last year. Soil sensors report low moisture levels.",
    actionLabel: "Check Sensors",
  },
  {
    id: "i3",
    type: "neutral",
    title: "Harvest Projection",
    description: "Based on current growth rates, harvest window for Corn is projected to open Oct 12 - Oct 15.",
  },
];

// Cattle Listings
export const CATTLE: CattleListing[] = [
  {
    id: "c1",
    name: "Bella",
    breed: "Holstein Friesian",
    category: "Dairy",
    age: "4 years",
    weight: 550,
    price: 85000,
    healthStatus: "Healthy",
    seller: "Raj Kumar",
    location: "Salem, TN",
    imageUrl: "https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?q=80&w=2670&auto=format&fit=crop",
  },
  {
    id: "c2",
    name: "Gauri",
    breed: "Gir",
    category: "Dairy",
    age: "3 years",
    weight: 480,
    price: 72000,
    healthStatus: "Vaccinated",
    seller: "Suresh Patel",
    location: "Erode, TN",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/64/Gir_02.JPG",
  },
  {
    id: "c3",
    name: "Lakshmi",
    breed: "Sahiwal",
    category: "Dairy",
    age: "5 years",
    weight: 420,
    price: 65000,
    healthStatus: "Healthy",
    seller: "Meena Devi",
    location: "Namakkal, TN",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/52/Sahiwala_01.JPG",
  },
  {
    id: "c4",
    name: "Veera",
    breed: "Kangayam",
    category: "Dual Purpose",
    age: "4 years",
    weight: 500,
    price: 95000,
    healthStatus: "Vaccinated",
    seller: "Vijay Reddy",
    location: "Dharmapuri, TN",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Kangayam_01.JPG",
  },
  {
    id: "c5",
    name: "Sundari",
    breed: "Jersey Cross",
    category: "Dairy",
    age: "3 years",
    weight: 400,
    price: 55000,
    healthStatus: "Under Treatment",
    seller: "Karthik Farms",
    location: "Coimbatore, TN",
    imageUrl: "https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?q=80&w=2521&auto=format&fit=crop",
  },
];

// Community Posts
export const COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "p1",
    author: "Rajesh Sharma",
    authorAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCk4wl1QwR6U0Trv1hTG7QralNDkeZ7b6BxmOOu4N03SvWdezUz6Aim8ASl_-11KNwaod6UsiD7Nkx_gJSzrLWglADEnpIps7LW4CUR_aEGHGp23teU3sF2LDpaem0kAzfbq8ADqcsoGtCEhVOHTHyw2Vbw0SsrEQKR0wjA8KRK4ybMmXvxVF4Jo_nqrTis1prbFwnr0HBaX3HAjNxAiJAGA0RzllagDsME4e1o-8gd4JSGfcer9VNpmiDxAEqGcs7N-EEO573p67Vl",
    content: "Just harvested my first batch of organic tomatoes this season! The drip irrigation system made a huge difference. Yield is up 30% compared to last year. Happy to share my setup details with anyone interested.",
    timestamp: "2023-10-24T08:30:00Z",
    likes: 42,
    comments: 8,
    tags: ["Organic", "Tomatoes", "Irrigation"],
  },
  {
    id: "p2",
    author: "Priya Nair",
    authorAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDEpsGH1EPzxHWTeVlm-1pZkYTSAShYzajtoy01A05kTd_9feZSdXBknbQREJDv5V-CMe7d6ZHwOxzDjyg_A_Pf70UFsr9RgN7FO_o3hKYZL--G82GFx9iP3B03aGkGd-NYHoksCJC1MygMRb4Cj_OY0VmudnLtpVq_3VeBugGIXt3cTaTn0I0h0qHGFdzajIwln0TvzzQeMM94MA6OO2yM03tlqr6mfkTKME3TtMPY0IzLAhIWBx8g1iMlAbiZFwOCmFv2uVvmwOsM",
    content: "Warning to farmers in Salem district: Spotted fall armyworm in my maize field. Applied neem oil spray as first response. Has anyone tried Beauveria bassiana for biological control? Looking for advice.",
    timestamp: "2023-10-23T16:45:00Z",
    likes: 67,
    comments: 23,
    tags: ["Pest Control", "Maize", "Help"],
  },
  {
    id: "p3",
    author: "Mohammed Ismail",
    authorAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAbcnNLaLYOzGiVp_ulJAoda2jUKYEmgk0r1NZv3iQMeqjssbTNFjHVKdEMEY-Tvb_1gnUxC43-6Hulikxo0L0WZ_5DX5wPPNE_2RacrgqbQ3ZXjN4fJxaRR4VbbXJEU1myds-XSKe-r6erWbJ2ZK6TX426Y2HRdTEquZU9T_lw2CXQ663T5Fio8IYR4S2lNkvjw2_GuxGcXETakAwR-HrIRWrvPr-KMHNU9kEpMWS8zZvhzNl9M9hsVhiqJGmGZdTePSQFxpNke9vP",
    content: "PM-KISAN installment received today! For those who haven't applied yet, the deadline for the current cycle is Nov 30. Make sure your Aadhaar is linked to your bank account. I can help with the application process.",
    timestamp: "2023-10-23T11:20:00Z",
    likes: 128,
    comments: 45,
    tags: ["Government Scheme", "PM-KISAN", "Finance"],
  },
  {
    id: "p4",
    author: "Anita Krishnan",
    authorAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDEpsGH1EPzxHWTeVlm-1pZkYTSAShYzajtoy01A05kTd_9feZSdXBknbQREJDv5V-CMe7d6ZHwOxzDjyg_A_Pf70UFsr9RgN7FO_o3hKYZL--G82GFx9iP3B03aGkGd-NYHoksCJC1MygMRb4Cj_OY0VmudnLtpVq_3VeBugGIXt3cTaTn0I0h0qHGFdzajIwln0TvzzQeMM94MA6OO2yM03tlqr6mfkTKME3TtMPY0IzLAhIWBx8g1iMlAbiZFwOCmFv2uVvmwOsM",
    content: "Completed my 3-acre banana plantation setup with tissue culture saplings. Total cost was around ₹2.5L including drip system. Expected first harvest in 12 months. Documenting the entire journey for anyone planning the same.",
    timestamp: "2023-10-22T14:00:00Z",
    likes: 89,
    comments: 31,
    tags: ["Banana", "Plantation", "Guide"],
  },
  {
    id: "p5",
    author: "Subramaniam V",
    authorAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCk4wl1QwR6U0Trv1hTG7QralNDkeZ7b6BxmOOu4N03SvWdezUz6Aim8ASl_-11KNwaod6UsiD7Nkx_gJSzrLWglADEnpIps7LW4CUR_aEGHGp23teU3sF2LDpaem0kAzfbq8ADqcsoGtCEhVOHTHyw2Vbw0SsrEQKR0wjA8KRK4ybMmXvxVF4Jo_nqrTis1prbFwnr0HBaX3HAjNxAiJAGA0RzllagDsME4e1o-8gd4JSGfcer9VNpmiDxAEqGcs7N-EEO573p67Vl",
    content: "Soil testing results are in: pH 6.8, NPK levels adequate. Recommended to add zinc sulfate before paddy transplanting. The local KVK is offering free soil testing until Dec 15 — highly recommend getting yours done.",
    timestamp: "2023-10-21T09:15:00Z",
    likes: 56,
    comments: 12,
    tags: ["Soil Health", "Tips", "KVK"],
  },
];

// Marketplace Items
export const MARKETPLACE_ITEMS: MarketplaceItem[] = [
  {
    id: "mp1",
    name: "Hybrid Tomato Seeds (10g)",
    category: "Seeds",
    price: 180,
    originalPrice: 220,
    seller: "KrishiMart",
    rating: 4.5,
    reviewCount: 342,
    inStock: true,
    description: "High-yield hybrid variety, suitable for all seasons. Disease resistant.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/70/Wikibooks_planting-tomato_seed.JPG",
  },
  {
    id: "mp2",
    name: "NPK 19-19-19 Fertilizer (25kg)",
    category: "Fertilizers",
    price: 1250,
    seller: "AgriSupply Co",
    rating: 4.8,
    reviewCount: 891,
    inStock: true,
    description: "Water-soluble complex fertilizer for balanced crop nutrition.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/75/NPK_Fertilizer.png",
  },
  {
    id: "mp3",
    name: "Battery Sprayer 16L",
    category: "Equipment",
    price: 3500,
    originalPrice: 4200,
    seller: "FarmTools Direct",
    rating: 4.2,
    reviewCount: 156,
    inStock: true,
    description: "Rechargeable 12V battery sprayer, 5 hr runtime, adjustable nozzle.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/89/Knapsack_sprayer.jpg",
  },
  {
    id: "mp4",
    name: "Neem Oil Pesticide (1L)",
    category: "Pesticides",
    price: 350,
    seller: "OrganicFarm Store",
    rating: 4.6,
    reviewCount: 523,
    inStock: true,
    description: "Cold-pressed neem oil, 1500ppm azadirachtin. Organic certified.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Neem_oil.jpg",
  },
  {
    id: "mp5",
    name: "Drip Irrigation Kit (1 acre)",
    category: "Equipment",
    price: 12500,
    originalPrice: 15000,
    seller: "JainIrrigation",
    rating: 4.7,
    reviewCount: 234,
    inStock: false,
    description: "Complete kit with mainline, sub-main, laterals, and emitters.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Drip_irrigation.jpg",
  },
  {
    id: "mp6",
    name: "Paddy Seeds IR-64 (5kg)",
    category: "Seeds",
    price: 420,
    seller: "StateAgriDept",
    rating: 4.3,
    reviewCount: 678,
    inStock: true,
    description: "Government certified high-yield paddy variety. 120-day crop.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Rice_Paddy_Closeup.jpg",
  },
  {
    id: "mp7",
    name: "Pruning Shears (Bypass)",
    category: "Tools",
    price: 650,
    originalPrice: 800,
    seller: "FarmTools Direct",
    rating: 4.4,
    reviewCount: 89,
    inStock: true,
    description: "Japanese steel blades, ergonomic grip. Ideal for fruit trees.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/15/Pruning_shears.jpg",
  },
  {
    id: "mp8",
    name: "Vermicompost (50kg)",
    category: "Fertilizers",
    price: 500,
    seller: "OrganicFarm Store",
    rating: 4.9,
    reviewCount: 1023,
    inStock: true,
    description: "Premium quality vermicompost. Rich in humic acid and micronutrients.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/61/Sifted_vermicompost_vermicast.png",
  },
];

// Rental Equipment
export const RENTAL_EQUIPMENT: RentalEquipment[] = [
  {
    id: "r1",
    name: "Mahindra 575 DI",
    type: "Tractor",
    pricePerDay: 2500,
    available: true,
    rating: 4.6,
    location: "Salem, TN",
    specs: "47 HP · 4WD · 8 Fwd + 2 Rev Gears",
    owner: "Kumar Rentals",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/20/Mahindra_tractor_model2.jpg",
  },
  {
    id: "r2",
    name: "Kubota DC-70 Plus",
    type: "Harvester",
    pricePerDay: 8000,
    available: true,
    rating: 4.8,
    location: "Erode, TN",
    specs: "70 HP · 1.4m Cutting Width · Auto Thresher",
    owner: "AgriMech Services",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/17/Kubota_DC-60.jpg",
  },
  {
    id: "r3",
    name: "Rotavator 5ft",
    type: "Tiller",
    pricePerDay: 1200,
    available: false,
    rating: 4.3,
    location: "Namakkal, TN",
    specs: "42 Blades · Fits 35-55 HP · 5ft Width",
    owner: "Ravi Equipment",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Rotary_tiller_compact.jpg",
  },
  {
    id: "r4",
    name: "Boom Sprayer 600L",
    type: "Sprayer",
    pricePerDay: 1800,
    available: true,
    rating: 4.5,
    location: "Coimbatore, TN",
    specs: "600L Tank · 12m Boom · PTO Driven",
    owner: "SprayTech Farm",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/04/Self_Propelled_Sprayer_made_by_Equipment_Technologies.jpg",
  },
  {
    id: "r5",
    name: "Seed Drill 9-Row",
    type: "Seeder",
    pricePerDay: 1500,
    available: true,
    rating: 4.4,
    location: "Dharmapuri, TN",
    specs: "9 Rows · Adjustable Spacing · Fertilizer Box",
    owner: "Kumar Rentals",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Disc_Harrow_Seed_Drill.jpg",
  },
  {
    id: "r6",
    name: "John Deere 5310",
    type: "Tractor",
    pricePerDay: 3500,
    available: false,
    rating: 4.9,
    location: "Salem, TN",
    specs: "55 HP · 4WD · Power Steering · AC Cabin",
    owner: "AgriMech Services",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c5/John_Deere_6900_tractor.JPG",
  },
];

// Harvest Records
export const HARVEST_RECORDS: HarvestRecord[] = [
  {
    id: "h1",
    fieldId: "f2",
    fieldName: "Field B",
    crop: "Winter Wheat",
    date: "2026-02-12",
    time: "10:30",
    weightTons: 18.5,
    moisturePercent: 12.4,
    qualityGrade: "A",
    notes: "Excellent quality. Clean harvest, no debris.",
  },
  {
    id: "h2",
    fieldId: "f3",
    fieldName: "Field C",
    crop: "Corn",
    date: "2026-02-10",
    time: "14:00",
    weightTons: 24.2,
    moisturePercent: 14.8,
    qualityGrade: "B",
    notes: "Slightly higher moisture. Needs drying before storage.",
  },
  {
    id: "h3",
    fieldId: "f1",
    fieldName: "Field A",
    crop: "Soybeans",
    date: "2026-02-08",
    time: "09:15",
    weightTons: 12.8,
    moisturePercent: 11.2,
    qualityGrade: "A",
  },
  {
    id: "h4",
    fieldId: "f2",
    fieldName: "Field B",
    crop: "Winter Wheat",
    date: "2026-02-05",
    time: "11:00",
    weightTons: 16.3,
    moisturePercent: 13.1,
    qualityGrade: "B",
    notes: "Second pass. Some grain left from first harvest.",
  },
  {
    id: "h5",
    fieldId: "f3",
    fieldName: "Field C",
    crop: "Corn",
    date: "2026-01-28",
    time: "08:45",
    weightTons: 22.0,
    moisturePercent: 15.6,
    qualityGrade: "C",
    notes: "Early harvest. Moisture too high, needs immediate processing.",
  },
];
